[green_agent]
agentbeats_id = "019bc5a4-101d-7e73-a9cc-9dc5aaaa65b1"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019d393d-06e2-7ce1-a69d-9c99bb6269ca"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "airline"
num_tasks = 3
